version: '3'
services:
  web:
    container_name: web
    depends_on:
      - db
    build: ./backend/
    ports:
      - "3005:3005"  
  db:
    container_name: db
    build: ./database/
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306" 
    restart: always
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        MYSQL_DATABASE: beers
        MYSQL_USER: user